### ISSUE TITLE
whoosh.index.LockError

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#218]
the user-agent for alice on try.pix is throwing this error:
```
2015-01-05 15:27:52+0000 [HTTPChannel,2,172.17.42.1] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 238, in render
	    body = resrc.render(self)
	  File "/usr/lib/python2.7/dist-packages/klein/resource.py", line 124, in render
	    d = defer.maybeDeferred(_execute)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/lib/python2.7/dist-packages/klein/resource.py", line 118, in _execute
	    **kwargs)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/lib/python2.7/dist-packages/klein/app.py", line 100, in execute_endpoint
	    return endpoint_f(self._instance, *args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/klein/app.py", line 185, in _f
	    return _call(instance, f, request, *a, **kw)
	  File "/usr/lib/python2.7/dist-packages/klein/app.py", line 27, in _call
	    return f(*args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/pixelated/controllers/mails_controller.py", line 104, in mail_tags
	    self._search_engine.index_mail(mail)
	  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/search/__init__.py", line 115, in index_mail
	    with self._index.writer() as writer:
	  File "/usr/lib/python2.7/dist-packages/whoosh/index.py", line 464, in writer
	    return SegmentWriter(self, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 502, in __init__
	    raise LockError
	whoosh.index.LockError: 
```

The problem now is, that tags are not shown in the taglist

**Comment by cz8s** [comment]
I don't really know what to do about it?
Can someone with more clue look into it?

**Comment by dudadornelles** [comment]
to fix it for now probably recreating the docker image should do it since
it will recreate the whoosh index.

any idea on when this started to happen?

On Mon, Jan 5, 2015 at 1:32 PM, Christoph <notifications@github.com> wrote:

> I don't really know what to do about it?
> Can someone with more clue look into it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated-project/pixelated-user-agent/issues/218#issuecomment-68723678>
> .
>



-- 
Duda Dornelles
Software Developer/Consultant @ ThoughtWorks

**Comment by cz8s** [comment]
I thought somebody might want to have a look before I delete everything.
The problem started after I added some tags.
Otherwise it was a new docker image.

**Comment by fbernitt** [comment]
Not reproducable for now.
