### ISSUE TITLE
Fix Vagrant installation from source

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#225]
we need to configure wheezy-backports for nodejs-legacy

```
==> source: Running Puppet with source.pp...
==> source: stdin: is not a tty
==> source: notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x287A1542472DC0E3_packages@pixelated-project.org.asc]/ensure: defined content as '{md5}3f582be03f19efaed603b70e9da67a27'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[add_pixelated_key]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/leap.list]/ensure: defined content as '{md5}760e91ebd9de5a10d78fb9977885cb1b'
==> source: notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x1E34A1828E20790_leap_archive_key]/ensure: defined content as '{md5}e6adbeab3ca4844502e78ef4eac7281d'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[add_leap_key]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/pixelated.list]/ensure: defined content as '{md5}9c35063a04a4014a549eb829e902280a'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[apt_get_update]: Triggered 'refresh' from 4 events
==> source: notice: /Stage[main]/Pixelated::Apt/Package[leap-keyring]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Common/Package[rng-tools]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Common/File[/etc/default/rng-tools]/content: content changed '{md5}29a6dfb91ef76469550026ea912f9307' to '{md5}23f177b3cdf1fe2f87caf3b2e6922722'
==> source: notice: /Stage[main]/Pixelated::Common/Service[rng-tools]/ensure: ensure changed 'stopped' to 'running'
==> source: notice: /Stage[main]/Pixelated::Source/Package[git]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[ruby-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[python-virtualenv]/ensure: ensure changed 'purged' to 'latest'
==> source: err: /Stage[main]/Pixelated::Source/Package[nodejs-legacy]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install nodejs-legacy' returned 100: Reading package lists...
==> source: Building dependency tree...
==> source: Reading state information...
==> source: Package nodejs-legacy is not available, but is referred to by another package.
==> source: This may mean that the package is missing, has been obsoleted, or
==> source: is only available from another source
==> source: 
==> source: E: Package 'nodejs-legacy' has no installation candidate
==> source:  at /tmp/vagrant-puppet-3/modules-0/pixelated/manifests/source.pp:13
==> source: notice: /Stage[main]/Pixelated::Source/Package[python-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: err: /Stage[main]/Pixelated::Source/Package[npm]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install npm' returned 100: Reading package lists...
==> source: Building dependency tree...
==> source: Reading state information...
==> source: E: Unable to locate package npm
==> source:  at /tmp/vagrant-puppet-3/modules-0/pixelated/manifests/source.pp:13
==> source: notice: /Stage[main]/Pixelated::Source/Package[libffi-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[compass]/ensure: created
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]: Dependency Package[npm] has failures: true
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]: Dependency Package[nodejs-legacy] has failures: true
==> source: warning: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]: Skipping because of failed dependencies
==> source: notice: Finished catalog run in 113.89 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by varac** [comment]
npm is only available in debian jessie

**Comment by varac** [comment]
ok, this is what i get with a jessie box:

```
--- git/pixelated-user-agent ‹vagrant_multimachine* M⁇› » vagrant provision source                                                                                                                             1 ↵
==> source: Running provisioner: puppet...
==> source: Running Puppet with source.pp...
==> source: stdin: is not a tty
==> source: Warning: Setting manifestdir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> source:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:260:in `block (2 levels) in parse_global_options')
==> source: Notice: Compiled catalog for debian-jessie.beta1-amd64-netboot in environment production in 0.67 seconds
==> source: Notice: /Stage[main]/Pixelated::Common/Service[rng-tools]/ensure: ensure changed 'stopped' to 'running'
==> source: Notice: /Stage[main]/Pixelated::Source/Package[compass]/ensure: created
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: /usr/bin/node
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: /usr/bin/npm
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: /usr/bin/ruby
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: /usr/bin/virtualenv
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: /usr/bin/git
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: /usr/bin/gpg
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: /usr/local/bin/compass
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: npm WARN package.json pixelated-user-agent-web-ui@0.0.0 No description
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: npm WARN package.json pixelated-user-agent-web-ui@0.0.0 No repository field.
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: npm WARN package.json pixelated-user-agent-web-ui@0.0.0 No README data
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: bower                          no-home HOME not set, user configuration will not be loaded
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: > pixelated-user-agent-web-ui@0.0.0 build /vagrant/web-ui
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: > npm run clean && npm run handlebars && npm run compass
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: > pixelated-user-agent-web-ui@0.0.0 clean /vagrant/web-ui
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: > rm -rf .tmp/ dist/**/* app/js/generated/hbs/* app/css/*
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: > pixelated-user-agent-web-ui@0.0.0 handlebars /vagrant/web-ui
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: > mkdir -p app/js/generated/hbs/ && handlebars app/templates/**/*.hbs > app/js/generated/hbs/templates.js --namespace=window.Pixelated --root .
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: > pixelated-user-agent-web-ui@0.0.0 compass /vagrant/web-ui
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: > compass compile
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns:     write app/css/foundation.css
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns:     write app/css/main.css
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns:     write app/css/news-cycle.css
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: DEPRECATION WARNING on line 47, column 82 of /vagrant/web-ui/app/scss/opensans.scss:
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: To include a newline in a string, use "\a" or "\a " as in CSS.
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: 
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns:     write app/css/opensans.css
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns:     write app/css/reset.css
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns:     write app/css/style-guide.css
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns:     write app/css/styles.css
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: New python executable in .virtualenv/bin/python2
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Not overwriting existing python script .virtualenv/bin/python (you must use .virtualenv/bin/python2)
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Installing setuptools, pip...done.
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Overwriting .virtualenv/bin/activate with new content
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Overwriting .virtualenv/bin/activate.fish with new content
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Overwriting .virtualenv/bin/activate.csh with new content
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Running virtualenv with interpreter /usr/bin/python2
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: /vagrant/install-pixelated.sh: /vagrant/service/.virtualenv/bin/pip: /tmp/pixelated-user-agent/service/.virtualenv/bin/python2: bad interpreter: No such file or directory
==> source: Error: /bin/bash /vagrant/install-pixelated.sh returned 126 instead of one of [0]
==> source: Error: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: change from notrun to 0 failed: /bin/bash /vagrant/install-pixelated.sh returned 126 instead of one of [0]
==> source: Notice: Finished catalog run in 332.91 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by varac** [comment]
ic, this error shows up when there's already an existing .virtualenv (i.e. from executing install-pixelated.sh on the host itself). we should use a dedicated directory for installing the .virtualenv on the vagrant box, and not use /vagrant because of this.

**Comment by varac** [comment]
i tested removing the old .virtualenv and now the script works fine.

**Comment by bwgpro** [comment]
Oh yes, I managed to make it work here too last week. I also added a line to the install script to remove the .virtualenv folder, before creating the new one

**Comment by varac** [comment]
i added a warning in the `Quickstart - Using Vagrant` section in the README.md saying: 

"be sure to remove an existing service/.virtualenv that you may have created installing the useragent on the vagrant *host* itself beforehand"

Is this enough for closing this ticket ?

**Comment by bwgpro** [comment]
I added it automatically instead of asking the user to check. I think it is better this way

**Comment by varac** [comment]
ic, the install script now removes the complete .virtualenv

**Comment by varac** [comment]
ok, "vagrant up source" should work now in my branch (https://github.com/varac/pixelated-user-agent/tree/vagrant_multimachine). if this works in QA and the installation as .deb too, this branch can get merged.

**Comment by varac** [comment]
oh, before merging, i would like to squash some commits. so please QA and ping me so i can merge.

**Comment by fbernitt** [comment]
Failed for me:

==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: New python executable in .virtualenv/bin/python2
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Also creating executable in .virtualenv/bin/python
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Installing setuptools, pip...done.
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Running virtualenv with interpreter /usr/bin/python2
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
==> source: Notice: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: Storing debug log for failure in /home/vagrant/.pip/pip.log
==> source: Error: /bin/bash /vagrant/install-pixelated.sh returned 1 instead of one of [0]
==> source: Error: /Stage[install_pixelated]/Pixelated::Source::Install_pixelated/Exec[install-pixelated]/returns: change from notrun to 0 failed: /bin/bash /vagrant/install-pixelated.sh returned 1 instead of one of [0]
==> source: Notice: Finished catalog run in 335.80 seconds

**Comment by bwgpro** [comment]
We migrated back to setup.py, this is why this one failed, I fixed it on master, a simple rebase should fix it

**Comment by bwgpro** [comment]
@varac can you create the pull request then we discuss, do what is needed there?

**Comment by varac** [comment]
i merged my branch today. now i get this; 

```
(.virtualenv)root@Debian-jessie:/vagrant/service# pixelated-user-agent 
Traceback (most recent call last):
  File "/vagrant/service/.virtualenv/bin/pixelated-user-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: enum34

```

**Comment by varac** [comment]
bwagner: could you take over to fix this pls ?

**Comment by bwgpro** [comment]
We remove enum34 because soledad uses some enums, and does not handle the new format yet (there is an accepted pull request for that)

**Comment by varac** [comment]
@bwgpro: could you link to the pull req pls ?

**Comment by bwgpro** [comment]
This issue https://leap.se/code/issues/6601

And in leap mail https://github.com/leapcode/leap_mail/pull/159

**Comment by varac** [comment]
@bwgpro   so what's the state here ? we need to wait for bitmask 0.8 to arrive, and then integrate the leap_mail code ?

**Comment by bwgpro** [comment]
I am still taking a look at this

**Comment by cz8s** [comment]
bwgpro wrote in irc: the problem now is that with enum34 we cannot run the tests, and without it we cannot run the user agent

**Comment by cz8s** [comment]
waiting until we know how to build user-agent correctly :)

**Comment by dudadornelles** [comment]
Build is green :)

**Comment by cz8s** [comment]
I still get a warning about service_identity missing.
But that is on purpose.
```
vagrant@vagrant-debian:/vagrant$ source service/.virtualenv/bin/activate
(.virtualenv)vagrant@vagrant-debian:/vagrant$ pixelated-user-agent --help
/vagrant/service/.virtualenv/local/lib/python2.7/site-packages/Twisted-14.0.2-py2.7-linux-x86_64.egg/twisted/internet/_sslverify.py:184: UserWarning: You do not have the service_identity module installed. Please install it from <https://pypi.python.org/pypi/service_identity>. Without the service_identity module and a recent enough pyOpenSSL tosupport it, Twisted can perform only rudimentary TLS client hostnameverification.  Many valid certificate/hostname mappings may be rejected.
```

But the user-agent works now
