### ISSUE TITLE
python-cryptography not available in debian

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#226]
```
root@leap-debian:~# pixelated-user-agent 
Traceback (most recent call last):
  File "/usr/bin/pixelated-user-agent", line 9, in <module>
    load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-user-agent')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pixelated/runserver.py", line 30, in <module>
    from pixelated.config import app_factory
  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 29, in <module>
    from pixelated.adapter.soledad.soledad_querier import SoledadQuerier
  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/soledad/soledad_querier.py", line 18, in <module>
    from pixelated.adapter.soledad.soledad_search_key_masterkey_retrieval_mixin import SoledadSearchIndexMasterkeyRetrievalMixin
  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/soledad/soledad_search_key_masterkey_retrieval_mixin.py", line 17, in <module>
    from cryptography.fernet import Fernet
ImportError: No module named cryptography.fernet
```

**Comment by varac** [comment]
ok, turns out that it would be easier to backport it. assigning to christoph.

**Comment by cz8s** [comment]
python-cryptography is not backportable. It build-depends on python-pretend which build-depends on pypy which does not work with the wheezy version of python.

**Comment by cz8s** [comment]
we need to find another way to create the keys

**Comment by bwgpro** [comment]
​maybe https://pynacl.readthedocs.org/en/latest/index.html ? ​Or we can do
it manually using python standard crypto libraries

Bruno W.G.
bwgpro@gmail.com
