### ISSUE TITLE
using vagrat and latest deb shows incomplete web interface

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#251]
i'll attach the screenshot in a minute.

see #197 for a similar error

**Comment by varac** [comment]
this is how it looks like: http://i.imgur.com/9MdHoF0.png

**Comment by varac** [comment]
i can reproduce it with 

```
vagrant destroy deb
vagrant up deb --provision
vagrant ssh deb
```
and then on the vm:

```
sudo wget --no-check-certificate https://dev.pixelated-project.org/ca.crt -O /usr/lib/python2.7/dist-packages/pixelated/certificates/dev.pixelated-project.org.ca.crt
pixelated-user-agent -c /vagrant/pixelated.cfg 

```

**Comment by lqust** [comment]
We have an issue to add an interstitial page while the UA is not fully loaded ( #237 ). Is it the same issue?

**Comment by varac** [comment]
btw, i experienced this using the  0.3~771.gbp163a97 .deb

**Comment by varac** [comment]
using the pixelated-useragent .deb 0.3~773.gbp309656 , built from @fbernitt's commit above, i now get this: 

```
vagrant@Debian-jessie:~$ pixelated-user-agent -c /vagrant/pixelated.cfg 
2015-01-26 14:52:02+0000 [-] Log opened.
2015-01-26 14:52:02+0000 [-] Site starting on 3333
2015-01-26 14:52:02+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7eff93a99e60>
2015-01-26 14:52:05+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 131, in <lambda>
	    reactor.callWhenRunning(lambda: init_app(app, args.home))
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 97, in init_app
	    leap_session = init_leap_session(app, leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 69, in init_leap_session
	    leap_home=leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 43, in open
	    session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 118, in create
	    session = self._create_new_session(credentials)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 128, in _create_new_session
	    soledad = SoledadSessionFactory.create(self._provider, auth, credentials.db_passphrase)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 50, in create
	    return SoledadSession(provider, encryption_passphrase, srp_session)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 59, in __init__
	    self.soledad = self._init_soledad(encryption_passphrase)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 70, in _init_soledad
	    local_db, server_url, which_bundle(self.provider), self.leap_srp_session.token, defer_encryption=False)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 286, in __init__
	    self._bootstrap()  # might raise BootstrapSequenceError()
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 432, in _bootstrap
	    self._init_db()
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 491, in _init_db
	    defer_encryption=self._defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 130, in open
	    cipher_page_size=cipher_page_size, defer_encryption=defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 415, in open_database
	    defer_encryption=defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 351, in _open_database
	    raise err  # go for the richest error?
	pysqlcipher.dbapi2.OperationalError: no such table: u1db_config

```

**Comment by varac** [comment]
ok, the last error resulted from a old .leap dir. i moved it out of the way and now it works.

**Comment by cz8s** [comment]
had to start the user-agent with ```--host 0.0.0.0```
