### ISSUE TITLE
u1db_config error on subsequent starts of debian package

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#258]
```
vagrant@Debian-jessie:~$ pixelated-user-agent -c /vagrant/pixelated.cfg 
2015-01-27 14:44:51+0000 [-] Log opened.
2015-01-27 14:44:51+0000 [-] Site starting on 3333
2015-01-27 14:44:51+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f0c5e39ad40>
2015-01-27 14:44:54+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 131, in <lambda>
	    reactor.callWhenRunning(lambda: init_app(app, args.home))
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 97, in init_app
	    leap_session = init_leap_session(app, leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 69, in init_leap_session
	    leap_home=leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 43, in open
	    session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 118, in create
	    session = self._create_new_session(credentials)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 128, in _create_new_session
	    soledad = SoledadSessionFactory.create(self._provider, auth, credentials.db_passphrase)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 50, in create
	    return SoledadSession(provider, encryption_passphrase, srp_session)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 59, in __init__
	    self.soledad = self._init_soledad(encryption_passphrase)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 70, in _init_soledad
	    local_db, server_url, which_bundle(self.provider), self.leap_srp_session.token, defer_encryption=False)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 286, in __init__
	    self._bootstrap()  # might raise BootstrapSequenceError()
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 432, in _bootstrap
	    self._init_db()
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 491, in _init_db
	    defer_encryption=self._defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 130, in open
	    cipher_page_size=cipher_page_size, defer_encryption=defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 415, in open_database
	    defer_encryption=defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 351, in _open_database
	    raise err  # go for the richest error?
	pysqlcipher.dbapi2.OperationalError: no such table: u1db_config

^C2015-01-27 14:45:44+0000 [-] Received SIGINT, shutting down.
2015-01-27 14:45:44+0000 [twisted.web.server.Site] (TCP Port 3333 Closed)
2015-01-27 14:45:44+0000 [twisted.web.server.Site] Stopping factory <twisted.web.server.Site instance at 0x7f0c5e39ad40>
2015-01-27 14:45:44+0000 [-] Main loop terminated.

vagrant@Debian-jessie:~$ rm -rf .leap

vagrant@Debian-jessie:~$ pixelated-user-agent -c /vagrant/pixelated.cfg 
2015-01-27 14:45:52+0000 [-] Log opened.
2015-01-27 14:45:52+0000 [-] Site starting on 3333
2015-01-27 14:45:52+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f2d582f5d40>
2015-01-27 14:45:54+0000 [-] No handlers could be found for logger "leap.soledad.client"
2015-01-27 14:45:56+0000 [-] SMTPFactory starting on 4650
2015-01-27 14:45:56+0000 [-] Starting factory <leap.mail.smtp.gateway.SMTPFactory instance at 0x7f2d5cb3b320>
2015-01-27 14:45:57+0000 [-] FETCH: syncing soledad...
…

^C2015-01-27 14:46:19+0000 [-] Received SIGINT, shutting down.
2015-01-27 14:46:19+0000 [twisted.web.server.Site] (TCP Port 3333 Closed)
2015-01-27 14:46:19+0000 [twisted.web.server.Site] Stopping factory <twisted.web.server.Site instance at 0x7f2d582f5d40>
2015-01-27 14:46:19+0000 [leap.mail.smtp.gateway.SMTPFactory] (TCP Port 4650 Closed)
2015-01-27 14:46:19+0000 [leap.mail.smtp.gateway.SMTPFactory] Stopping factory <leap.mail.smtp.gateway.SMTPFactory instance at 0x7f2d5cb3b320>
2015-01-27 14:46:19+0000 [-] Main loop terminated.

vagrant@Debian-jessie:~$ pixelated-user-agent -c /vagrant/pixelated.cfg 
2015-01-27 14:46:23+0000 [-] Log opened.
2015-01-27 14:46:23+0000 [-] Site starting on 3333
2015-01-27 14:46:23+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f6356a15d40>
2015-01-27 14:46:25+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 416, in fireEvent
	    DeferredList(beforeResults).addCallback(self._continueFiring)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallback
	    callbackKeywords=kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 131, in <lambda>
	    reactor.callWhenRunning(lambda: init_app(app, args.home))
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 97, in init_app
	    leap_session = init_leap_session(app, leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 69, in init_leap_session
	    leap_home=leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 43, in open
	    session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 118, in create
	    session = self._create_new_session(credentials)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 128, in _create_new_session
	    soledad = SoledadSessionFactory.create(self._provider, auth, credentials.db_passphrase)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 50, in create
	    return SoledadSession(provider, encryption_passphrase, srp_session)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 59, in __init__
	    self.soledad = self._init_soledad(encryption_passphrase)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/soledad.py", line 70, in _init_soledad
	    local_db, server_url, which_bundle(self.provider), self.leap_srp_session.token, defer_encryption=False)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 286, in __init__
	    self._bootstrap()  # might raise BootstrapSequenceError()
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 432, in _bootstrap
	    self._init_db()
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/__init__.py", line 491, in _init_db
	    defer_encryption=self._defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 130, in open
	    cipher_page_size=cipher_page_size, defer_encryption=defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 415, in open_database
	    defer_encryption=defer_encryption)
	  File "/usr/lib/python2.7/dist-packages/leap/soledad/client/sqlcipher.py", line 351, in _open_database
	    raise err  # go for the richest error?
	pysqlcipher.dbapi2.OperationalError: no such table: u1db_config


```

**Comment by varac** [comment]
https://leap.se/code/issues/3619
https://leap.se/code/issues/5562

**Comment by dudadornelles** [comment]
I packaged it again and added it to our packages.pixelated-project.org wheezy-backports as python-sqlcipher_2.6.3.3+0~20141111222659.14+wheezy~1.gbp2d164a+pix1_amd64.deb.

This will be the version picked up when we install it on wheezy.

**Comment by dudadornelles** [comment]
To test it, get a wheezy box, add the pixelated+leap repos to sources.list

```
deb http://packages.pixelated-project.org/debian wheezy-snapshots main
deb http://packages.pixelated-project.org/debian wheezy-backports main
deb http://packages.pixelated-project.org/debian wheezy main
deb http://deb.bitmask.net/debian/ wheezy main
deb http://deb.leap.se/experimental wheezy main
```

and 

```shell
apt-get install pixelated-user-agent
```

Then start the app, play around with it and stop it. The restart it. It should work normally on restart (as opposed to breaking with a ` pysqlcipher.dbapi2.OperationalError: no such table: u1db_config` error).

**Comment by cz8s** [comment]
works

**Comment by cz8s** [comment]
we need to change the images we use for our tests now, but thats another issue
