### ISSUE TITLE
Use wheezy for vagrant source box

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#272]
the only dependency on jessie (as noted in the Vagrantfile) is: 

```
the source installation needs npm, which is also only available in debian jessie
```

this is true for the debian npm package, but we could install npm with the [official provided install script](https://www.npmjs.org/install.sh)

**Comment by varac** [comment]
hugh, i made it so far in my 272_use_wheezy_for_source_vagrant_vm branch:

```
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pixelated-user-agent 
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/bin/pixelated-user-agent", line 9, in <module>
    load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-user-agent')()
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/vagrant/service/pixelated/config/__init__.py", line 21, in <module>
    from pixelated.config import app_factory
  File "/vagrant/service/pixelated/config/app_factory.py", line 30, in <module>
    from pixelated.adapter.search import SearchEngine
  File "/vagrant/service/pixelated/adapter/search/__init__.py", line 17, in <module>
    from pixelated.support.encrypted_file_storage import EncryptedFileStorage
  File "/vagrant/service/pixelated/support/encrypted_file_storage.py", line 24, in <module>
    from leap.soledad.client.crypto import encrypt_sym
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/leap.soledad.client-0.6.3-py2.7.egg/leap/soledad/client/__init__.py", line 82, in <module>
    from leap.soledad.client.sqlcipher import open as sqlcipher_open
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/leap.soledad.client-0.6.3-py2.7.egg/leap/soledad/client/sqlcipher.py", line 57, in <module>
    from pysqlcipher import dbapi2
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/pysqlcipher-2.6.4-py2.7-linux-x86_64.egg/pysqlcipher/dbapi2.py", line 31, in <module>
    from pysqlcipher._sqlite import *
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/pysqlcipher-2.6.4-py2.7-linux-x86_64.egg/pysqlcipher/_sqlite.so)

```

**Comment by dudadornelles** [comment]
GLIBC version issues is a big problem and I wouldn't go down that path of fixing this. We already can run the deb from wheezy, I don't see why running the sources from it would be such an improvement.

That said I'll try it here to see if I can reproduce.

**Comment by varac** [comment]
ok, if you want to try my branch: https://github.com/varac/pixelated-user-agent/tree/272_use_wheezy_for_source_vagrant_vm

**Comment by dudadornelles** [comment]
@varac found the following issue:
```
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: Searching for jsonschema
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: Reading http://pypi.python.org/simple/jsonschema/
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: Best match: jsonschema 2.4.0
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: Downloading https://pypi.python.org/packages/source/j/jsonschema/jsonschema-2.4.0.zip#md5=f645c88123189976058fcf550c02e50f
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: Processing jsonschema-2.4.0.zip
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: Running jsonschema-2.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-DWR2Ra/jsonschema-2.4.0/egg-dist-tmp-L5QCff
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: Traceback (most recent call last):
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "setup.py", line 76, in <module>
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     include_package_data=True
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     dist.run_commands()
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     self.run_command(cmd)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     cmd_obj.run()
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/develop.py", line 27, in run
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     self.install_for_development()
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/develop.py", line 105, in install_for_development
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     self.process_distribution(None, self.dist, not self.no_deps)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 673, in process_distribution
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     [requirement], self.local_index, self.easy_install
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 576, in resolve
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     dist = best[req.key] = env.best_match(req, self, installer)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 821, in best_match
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     return self.obtain(req, installer) # try and download/install
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 833, in obtain
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     return installer(requirement)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 589, in easy_install
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     return self.install_item(spec, dist.location, tmpdir, deps)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 619, in install_item
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     dists = self.install_eggs(spec, download, tmpdir)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 809, in install_eggs
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     return self.build_and_install(setup_script, setup_base)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 1086, in build_and_install
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     self.run_setup(setup_script, setup_base, args)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/easy_install.py", line 1075, in run_setup
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     run_setup(setup_script, args)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/sandbox.py", line 30, in run_setup
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     lambda: execfile(
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/sandbox.py", line 72, in run
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     return func()
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/sandbox.py", line 32, in <lambda>
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     {'__file__':setup_script, '__name__':'__main__'}
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "setup.py", line 3, in <module>
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     # Copyright (c) 2014 ThoughtWorks, Inc.
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/tmp/easy_install-DWR2Ra/jsonschema-2.4.0/jsonschema/__init__.py", line 18, in <module>
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/tmp/easy_install-DWR2Ra/jsonschema-2.4.0/jsonschema/validators.py", line 157, in <module>
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/tmp/easy_install-DWR2Ra/jsonschema-2.4.0/jsonschema/_utils.py", line 58, in load_schema
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:   File "/home/vagrant/user-agent-venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns:     return codecs.utf_8_decode(input, errors, True)
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: AttributeError: 'NoneType' object has no attribute 'utf_8_decode'
```

**Comment by dudadornelles** [comment]
followed by:
```
LAddornell:pixelated-user-agent ddornell$ vagrant ssh 
Linux leap-wheezy 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Feb 11 16:19:58 2015 from 10.0.2.2
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pixelated-user-agent 
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/bin/pixelated-user-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jsonschema
```

**Comment by varac** [comment]
@dudadornelles no, i didn't had problems with jsonschema.

**Comment by varac** [comment]
same here, i pulled from the 272_use_wheezy_for_source_vagrant_vm, destroyed and started the source box, and ran into the jsonschema bug:

```
==> source: Running provisioner: puppet...
==> source: Running Puppet with source.pp...
==> source: stdin: is not a tty
==> source: notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x287A1542472DC0E3_packages@pixelated-project.org.asc]/ensure: defined content as '{md5}3f582be03f19efaed603b70e9da67a27'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[add_pixelated_key]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/preferences.d/pixelated]/ensure: defined content as '{md5}316b7bd2fd04ad7f565d4e7ad3bd6a43'
==> source: notice: /Stage[main]/Phantomjs/Exec[download_phantomjs]/returns: executed successfully
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/wheezy-backports.list]/ensure: defined content as '{md5}b30d79e4302dbfa2d7cf88299647b264'
==> source: notice: /Stage[main]/Phantomjs/Exec[unpack_phantomjs]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Phantomjs/Exec[install_phantomjs]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x1E34A1828E20790_leap_archive_key]/ensure: defined content as '{md5}c11c9804d356e86b7669a2a89181b32b'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[add_leap_key]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/leap.list]/ensure: defined content as '{md5}760e91ebd9de5a10d78fb9977885cb1b'
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/pixelated.list]/ensure: defined content as '{md5}8cb29b17201f94e1189805b7c6bbdbe6'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[apt_get_update]: Triggered 'refresh' from 6 events
==> source: notice: /Stage[main]/Pixelated::Apt/Package[leap-keyring]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Common/Package[haveged]/ensure: ensure changed 'purged' to 'present'
==> source: notice: /Stage[main]/Pixelated::Source/Package[libfontconfig1]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[git]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[ruby-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[libsqlite3-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[python-virtualenv]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[nodejs-legacy]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[python-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[libffi-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source::Npm/Exec[install_npm]/returns: executed successfully
==> source: notice: /Stage[main]/Pixelated::Source/Package[compass]/ensure: created
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/File[/home/vagrant/.activate_custom_node_modules.sh]/ensure: defined content as '{md5}096afed77d8565b9cb369ff1e7a93c9e'
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: executed successfully
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[add_custom_node_modules_to_bashrc]/returns: executed successfully
==> source: notice: Finished catalog run in 332.39 seconds
--- git/pixelated-user-agent ‹pixelated_272_use_wheezy_for_source_vagrant_vm* ⁇› » vagrant ssh source
Linux leap-wheezy 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Oct 31 00:41:42 2014 from 192.168.122.1
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pixelated-user-agent 
Traceback (most recent call last):
  File "/home/vagrant/user-agent-venv/bin/pixelated-user-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jsonschema

```

**Comment by dudadornelles** [comment]
going to /vagrant/service and running `./go setup --always-unzip` fixes it.

**Comment by dudadornelles** [comment]
I mean it installs `jsonschema` with no errors. The weird things is why can't it install it while provisioning?

**Comment by bwgpro** [comment]
Tested three times, vagrant upping from scratch, it is working now
