### ISSUE TITLE
Fix debian package dependencies in Vagrant deb box

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#278]
i'm trying to use debian wheezy for the vagrant deb box, and get this:

```
--- git/pixelated-user-agent ‹master* M⁇› » vagrant up deb     
Bringing machine 'deb' up with 'libvirt' provider...
==> deb: Creating image (snapshot of base box volume).
==> deb: Creating domain with the following settings...
==> deb:  -- Name:              pixelated-user-agent_deb
==> deb:  -- Domain type:       kvm
==> deb:  -- Cpus:              1
==> deb:  -- Memory:            500M
==> deb:  -- Base box:          leap-wheezy
==> deb:  -- Storage pool:      default
==> deb:  -- Image:             /home/varac/vagrant/storagepool/pixelated-user-agent_deb.img
==> deb:  -- Volume Cache:      default
==> deb:  -- Kernel:            
==> deb:  -- Initrd:            
==> deb:  -- Graphics Type:     vnc
==> deb:  -- Graphics Port:     5900
==> deb:  -- Graphics IP:       127.0.0.1
==> deb:  -- Graphics Password: Not defined
==> deb:  -- Video Type:        cirrus
==> deb:  -- Video VRAM:        9216
==> deb:  -- Command line : 
==> deb: Pruning invalid NFS exports. Administrator privileges will be required...
==> deb: Starting domain.
==> deb: Waiting for domain to get an IP address...
==> deb: Waiting for SSH to become available...
    deb: 
    deb: Vagrant insecure key detected. Vagrant will automatically replace
    deb: this with a newly generated keypair for better security.
    deb: 
    deb: Inserting generated public key within guest...
    deb: Removing insecure key from the guest if its present...
    deb: Key inserted! Disconnecting and reconnecting using new SSH key...
==> deb: Starting domain.
==> deb: Waiting for domain to get an IP address...
==> deb: Waiting for SSH to become available...
==> deb: Creating shared folders metadata...
==> deb: Forwarding ports...
==> deb: 3333 => 3333 (adapter eth0)
==> deb: Exporting NFS shared folders...
==> deb: Preparing to edit /etc/exports. Administrator privileges will be required...
nfsd running
exportfs: duplicated export entries:
exportfs: 	192.168.121.207:/home/varac/dev/projects/puppet/shared-modules
exportfs: 	192.168.121.207:/home/varac/dev/projects/puppet/shared-modules
exportfs: duplicated export entries:
exportfs: 	192.168.121.207:/home/varac/dev/projects/puppet/other-modules
exportfs: 	192.168.121.207:/home/varac/dev/projects/puppet/other-modules
exportfs: duplicated export entries:
exportfs: 	192.168.121.248:/home/varac/dev/projects/puppet/bitrigger/modules/site_config/manifests/vagrant
exportfs: 	192.168.121.248:/home/varac/dev/projects/puppet/bitrigger/modules/site_config/manifests/vagrant
exportfs: duplicated export entries:
exportfs: 	192.168.121.248:/home/varac/dev/projects/puppet/shared-modules
exportfs: 	192.168.121.248:/home/varac/dev/projects/puppet/shared-modules
exportfs: duplicated export entries:
exportfs: 	192.168.121.248:/home/varac/dev/projects/puppet/other-modules
exportfs: 	192.168.121.248:/home/varac/dev/projects/puppet/other-modules
==> deb: Mounting NFS shared folders...
==> deb: Configuring and enabling network interfaces...
==> deb: Running provisioner: puppet...
==> deb: Running Puppet with default.pp...
==> deb: stdin: is not a tty
==> deb: notice: /Stage[main]/Common::Moduledir/File[/var/lib/puppet/modules]/ensure: created
==> deb: notice: /File[/var/lib/puppet/modules/README]/ensure: defined content as '{md5}54000a2c832d3c13c1b6c5e2d4624644'
==> deb: notice: /Stage[main]//Package[tmux]/ensure: ensure changed 'purged' to 'present'
==> deb: notice: /Stage[main]//Package[vim]/ensure: ensure changed 'purged' to 'present'
==> deb: notice: /Stage[main]/Apt/Apt::Apt_conf[02show_upgraded]/File[/etc/apt/apt.conf.d/02show_upgraded]/ensure: defined content as '{md5}f8b9fbb99496bc2d919bb757b9819540'
==> deb: notice: /Stage[main]/Apt/File[/etc/apt/sources.list]/content: content changed '{md5}70426476236bc995be603f9ece064223' to '{md5}8caa45c8e8b54ce440ad988fe8310093'
==> deb: notice: /Stage[main]/Apt::Preferences/File[/etc/apt/preferences]/ensure: created
==> deb: notice: /Stage[main]/Apt/Apt::Apt_conf[03clean]/File[/etc/apt/apt.conf.d/03clean]/ensure: defined content as '{md5}9c94d212b6be1a8a08d1facc24424f8b'
==> deb: notice: /Stage[main]/Apt::Dot_d_directories/Exec[refresh_apt]: Triggered 'refresh' from 3 events
==> deb: notice: /Stage[main]/Apt/File[/var/cache/local]/ensure: created
==> deb: notice: /Stage[main]/Apt/File[/var/cache/local/preseeding]/ensure: created
==> deb: notice: /Stage[main]/Apt/Modules_dir[apt]/Module_dir[apt]/File[/var/lib/puppet/modules/apt]/ensure: created
==> deb: notice: /Stage[main]/Squid_deb_proxy::Client/Package[squid-deb-proxy-client]/ensure: ensure changed 'purged' to 'present'
==> deb: notice: Finished catalog run in 42.09 seconds
==> deb: Running provisioner: puppet...
==> deb: Running Puppet with deb.pp...
==> deb: stdin: is not a tty
==> deb: notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x287A1542472DC0E3_packages@pixelated-project.org.asc]/ensure: defined content as '{md5}3f582be03f19efaed603b70e9da67a27'
==> deb: notice: /Stage[main]/Pixelated::Apt/Exec[add_pixelated_key]: Triggered 'refresh' from 1 events
==> deb: notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x1E34A1828E20790_leap_archive_key]/ensure: defined content as '{md5}c11c9804d356e86b7669a2a89181b32b'
==> deb: notice: /Stage[main]/Pixelated::Apt/Exec[add_leap_key]: Triggered 'refresh' from 1 events
==> deb: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/leap.list]/ensure: defined content as '{md5}760e91ebd9de5a10d78fb9977885cb1b'
==> deb: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/pixelated.list]/ensure: defined content as '{md5}8cb29b17201f94e1189805b7c6bbdbe6'
==> deb: notice: /Stage[main]/Pixelated::Apt/Exec[apt_get_update]: Triggered 'refresh' from 4 events
==> deb: notice: /Stage[main]/Pixelated::Apt/Package[leap-keyring]/ensure: ensure changed 'purged' to 'latest'
==> deb: notice: /Stage[main]/Pixelated::Common/Package[haveged]/ensure: ensure changed 'purged' to 'present'
==> deb: err: /Stage[main]/Pixelated::Useragent/Package[pixelated-user-agent]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install pixelated-user-agent' returned 100: Reading package lists...
==> deb: Building dependency tree...
==> deb: Reading state information...
==> deb: Some packages could not be installed. This may mean that you have
==> deb: requested an impossible situation or if you are using the unstable
==> deb: distribution that some required packages have not yet been created
==> deb: or been moved out of Incoming.
==> deb: The following information may help to resolve the situation:
==> deb: 
==> deb: The following packages have unmet dependencies:
==> deb:  pixelated-user-agent : Depends: soledad-client but it is not going to be installed
==> deb:                         Depends: leap-mail but it is not going to be installed
==> deb:                         Depends: python-whoosh (>= 2.5.7) but 2.3.2-2 is to be installed
==> deb:                         Depends: python-twisted-web (>= 12.3.0) but 12.0.0-1 is to be installed
==> deb:                         Depends: python-twisted (>= 12.3.0) but 12.0.0-1 is to be installed
==> deb: E: Unable to correct problems, you have held broken packages.
==> deb:  at /tmp/vagrant-puppet/modules-f20d1267d99a620662dec6fbf8fd9639/pixelated/manifests/useragent.pp:4
==> deb: notice: Finished catalog run in 15.97 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by dudadornelles** [comment]
You just need official debia wheezy-backports

**Comment by varac** [comment]
@re-nobre if you move issues to QA, please remove any assignees, because in this case ppl would think i'll QA this issue, and i would wait for someone to pick it up.

**Comment by varac** [comment]
just as reference, this is the same as #271

**Comment by dudadornelles** [comment]
My previous commit adds the wheezy-backports repo to the sources and fixes it. I was able to start vagrant and run the app.

**Comment by varac** [comment]
@dudadornelles: thx for pointing this out - i was already using a backports sources that was put by my global Vagrantfile provisioning. 
I added 607627c that moves the wheezy-backports sources to dedicated file.
but the problem persists:

```
vagrant@leap-wheezy:/vagrant/config$ grep -v PASS try.pixelated-project.org.config
[pixelated]
HOST=0.0.0.0
PORT=3333
LEAP_USERNAME=varac
LEAP_SERVER_NAME=try.pixelated-project.org
vagrant@leap-wheezy:/vagrant/config$ pixelated-user-agent --config ./try.pixelated-project.org.config --leap-cert ./try.pixelated-project.org.ca.crt
2015-02-10 09:21:44+0000 [-] Log opened.
2015-02-10 09:21:44+0000 [-] Site starting on 3333
2015-02-10 09:21:44+0000 [-] Starting factory <twisted.web.server.Site instance at 0x243a5a8>
2015-02-10 09:21:44+0000 [-] Unhandled error in Deferred:
2015-02-10 09:21:44+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
	    self.__bootstrap_inner()
	  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 505, in run
	    self.__target(*self.__args, **self.__kwargs)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
	    result = context.call(ctx, function, *args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/__init__.py", line 63, in init_soledad
	    return init_soledad_and_user_key(app, args.home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/soledad.py", line 24, in init_soledad_and_user_key
	    leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 43, in open
	    session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 118, in create
	    session = self._create_new_session(credentials)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 125, in _create_new_session
	    self._provider.download_certificate_to('%s/ca.crt' % self._provider.config.leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 68, in download_certificate_to
	    cert = self.fetch_valid_certificate()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 73, in fetch_valid_certificate
	    cert = self._fetch_certificate()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 87, in _fetch_certificate
	    session.close()
	exceptions.AttributeError: 'Session' object has no attribute 'close'
	

```

@dudadornelles: when you said that you was able to run the app, did you actually succeeded to login/register to try.pix ?

**Comment by varac** [comment]
```
vagrant@leap-wheezy:/vagrant/config$ openssl x509  -noout -in try.pixelated-project.org.ca.crt -fingerprint
SHA1 Fingerprint=B8:70:AF:B7:B5:AB:01:DB:F7:99:4D:06:F0:C8:D3:AA:96:F2:43:CC
```

**Comment by dudadornelles** [comment]
Yes, I was able to run, connect to Leap and sync mails. Can you do
`apt--cache policy` on your soledad/leap mail pckgs

**Comment by varac** [comment]
everything works now from my side - see #279 too.

**Comment by dudadornelles** [comment]
Then everything works. It was working for me already with a fresh vagrant box.
