### ISSUE TITLE
Depend on python-requests from wheezy-backports

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#279]
i try using the vagrant deb box to connect to try.pixelated using an already registered user:

```
vagrant@leap-wheezy:/vagrant/config$ pixelated-user-agent --config ./try.pixelated-project.org.config --leap-cert ./try.pixelated-project.org.ca.crt 
2015-02-09 12:57:14+0000 [-] Log opened.
2015-02-09 12:57:14+0000 [-] Site starting on 3333
2015-02-09 12:57:14+0000 [-] Starting factory <twisted.web.server.Site instance at 0x28b54d0>
2015-02-09 12:57:14+0000 [-] Unhandled error in Deferred:
2015-02-09 12:57:14+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
	    self.__bootstrap_inner()
	  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 505, in run
	    self.__target(*self.__args, **self.__kwargs)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
	    result = context.call(ctx, function, *args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/__init__.py", line 63, in init_soledad
	    return init_soledad_and_user_key(app, args.home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/soledad.py", line 24, in init_soledad_and_user_key
	    leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 43, in open
	    session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 118, in create
	    session = self._create_new_session(credentials)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 125, in _create_new_session
	    self._provider.download_certificate_to('%s/ca.crt' % self._provider.config.leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 68, in download_certificate_to
	    cert = self.fetch_valid_certificate()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 73, in fetch_valid_certificate
	    cert = self._fetch_certificate()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 87, in _fetch_certificate
	    session.close()
	exceptions.AttributeError: 'Session' object has no attribute 'close'
```

**Comment by dudadornelles** [comment]
Couldn't reproduce it. Just created a deb box and everything works fine. Can you try again?

**Comment by varac** [comment]
damn, i *can* reproduce it using the latest master:

```
vagrant@leap-wheezy:/vagrant/config$ openssl x509  -noout -in try.pixelated-project.org.ca.crt -fingerprint
SHA1 Fingerprint=B8:70:AF:B7:B5:AB:01:DB:F7:99:4D:06:F0:C8:D3:AA:96:F2:43:CC


vagrant@leap-wheezy:/vagrant/config$ grep -v PASS try.pixelated-project.org.config
[pixelated]
HOST=0.0.0.0
PORT=3333
LEAP_USERNAME=varac
LEAP_SERVER_NAME=try.pixelated-project.org


vagrant@leap-wheezy:/vagrant/config$ pixelated-user-agent --config ./try.pixelated-project.org.config --leap-cert ./try.pixelated-project.org.ca.crt
2015-02-10 09:30:18+0000 [-] Log opened.
2015-02-10 09:30:18+0000 [-] Site starting on 3333
2015-02-10 09:30:18+0000 [-] Starting factory <twisted.web.server.Site instance at 0x28e4488>
2015-02-10 09:30:18+0000 [-] Unhandled error in Deferred:
2015-02-10 09:30:18+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
	    self.__bootstrap_inner()
	  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 505, in run
	    self.__target(*self.__args, **self.__kwargs)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
	    result = context.call(ctx, function, *args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/__init__.py", line 63, in init_soledad
	    return init_soledad_and_user_key(app, args.home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/soledad.py", line 24, in init_soledad_and_user_key
	    leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 43, in open
	    session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 118, in create
	    session = self._create_new_session(credentials)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 125, in _create_new_session
	    self._provider.download_certificate_to('%s/ca.crt' % self._provider.config.leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 68, in download_certificate_to
	    cert = self.fetch_valid_certificate()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 73, in fetch_valid_certificate
	    cert = self._fetch_certificate()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 87, in _fetch_certificate
	    session.close()
	exceptions.AttributeError: 'Session' object has no attribute 'close'
```

**Comment by varac** [comment]
ok, i know what the problem is now. i had a global puppet provisioning enabled, which installed squid-deb-proxy on all my vagrant machines to speed up downloads. this installed python-requests from wheezy (0.12.1-1+deb7u1). using this version, pixelated-useragent crashes reproducable:

```
vagrant@leap-wheezy:/vagrant/config$ apt-cache policy python-requests
python-requests:
  Installed: 2.0.0-1~bpo70+1
  Candidate: 2.0.0-1~bpo70+1
  Version table:
     2.0.0-1~bpo70+2 0
        100 http://http.debian.net/debian/ wheezy-backports/main amd64 Packages
 *** 2.0.0-1~bpo70+1 0
        500 http://deb.leap.se/0.6/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.12.1-1+deb7u1 0
        500 http://security.debian.org/ wheezy/updates/main amd64 Packages
     0.12.1-1 0
        500 http://http.debian.net/debian/ wheezy/main amd64 Packages

vagrant@leap-wheezy:/vagrant/config$ sudo -i

root@leap-wheezy:~# apt-get install python-requests=0.12.1-1+deb7u1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  python-urllib3
Use 'apt-get autoremove' to remove it.
The following extra packages will be installed:
  python-gevent python-greenlet python-oauthlib
Suggested packages:
  python-gevent-doc python-gevent-dbg python-greenlet-doc python-greenlet-dev python-greenlet-dbg
The following NEW packages will be installed:
  python-gevent python-greenlet python-oauthlib
The following packages will be DOWNGRADED:
  python-requests
0 upgraded, 3 newly installed, 1 downgraded, 0 to remove and 54 not upgraded.
Need to get 332 kB of archives.
After this operation, 926 kB of additional disk space will be used.
Do you want to continue [Y/n]? 
Get:1 http://security.debian.org/ wheezy/updates/main python-requests all 0.12.1-1+deb7u1 [56.3 kB]
Get:2 http://http.debian.net/debian/ wheezy/main python-oauthlib all 0.1.2-1 [27.4 kB]                              
Get:3 http://http.debian.net/debian/ wheezy/main python-greenlet amd64 0.3.1-2.5 [18.0 kB]              
Get:4 http://http.debian.net/debian/ wheezy/main python-gevent amd64 0.13.6-1+nmu3 [230 kB]
Fetched 332 kB in 0s (388 kB/s)        
Selecting previously unselected package python-oauthlib.
(Reading database ... 52248 files and directories currently installed.)
Unpacking python-oauthlib (from .../python-oauthlib_0.1.2-1_all.deb) ...
dpkg: warning: downgrading python-requests from 2.0.0-1~bpo70+1 to 0.12.1-1+deb7u1
Preparing to replace python-requests 2.0.0-1~bpo70+1 (using .../python-requests_0.12.1-1+deb7u1_all.deb) ...
Unpacking replacement python-requests ...
Selecting previously unselected package python-greenlet.
Unpacking python-greenlet (from .../python-greenlet_0.3.1-2.5_amd64.deb) ...
Selecting previously unselected package python-gevent.
Unpacking python-gevent (from .../python-gevent_0.13.6-1+nmu3_amd64.deb) ...
Setting up python-oauthlib (0.1.2-1) ...
Setting up python-requests (0.12.1-1+deb7u1) ...
Setting up python-greenlet (0.3.1-2.5) ...
Setting up python-gevent (0.13.6-1+nmu3) ...
Processing triggers for python-support ...
root@leap-wheezy:~# logout

vagrant@leap-wheezy:/vagrant/config$ pixelated-user-agent --config ./try.pixelated-project.org.config 
2015-02-10 10:28:54+0000 [-] Log opened.
2015-02-10 10:28:54+0000 [-] Site starting on 3333
2015-02-10 10:28:54+0000 [-] Starting factory <twisted.web.server.Site instance at 0x2d93488>
2015-02-10 10:28:55+0000 [-] Unhandled error in Deferred:
2015-02-10 10:28:55+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
	    self.__bootstrap_inner()
	  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 505, in run
	    self.__target(*self.__args, **self.__kwargs)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
	    result = context.call(ctx, function, *args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/__init__.py", line 63, in init_soledad
	    return init_soledad_and_user_key(app, args.home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/config/soledad.py", line 24, in init_soledad_and_user_key
	    leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 43, in open
	    session = LeapSessionFactory(provider).create(LeapCredentials(username, password))
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 118, in create
	    session = self._create_new_session(credentials)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 125, in _create_new_session
	    self._provider.download_certificate_to('%s/ca.crt' % self._provider.config.leap_home)
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 68, in download_certificate_to
	    cert = self.fetch_valid_certificate()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 73, in fetch_valid_certificate
	    cert = self._fetch_certificate()
	  File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 87, in _fetch_certificate
	    session.close()
	exceptions.AttributeError: 'Session' object has no attribute 'close'

```


the problem is that pixelated-useragent doesn't depend on the backports version of python-requests. i'll change the topic according to this.

**Comment by varac** [comment]
ok, should be fine now

**Comment by dudadornelles** [comment]
After a fresh vagrant up deb I do:
```
vagrant@leap-wheezy:~$ apt-cache policy python-requests
python-requests:
  Installed: 2.0.0-1~bpo70+2
  Candidate: 2.0.0-1~bpo70+2
  Package pin: 2.0.0-1~bpo70+2
  Version table:
 *** 2.0.0-1~bpo70+2 999
        100 http://http.debian.net/debian/ wheezy-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.0-1~bpo70+1 999
        500 http://deb.leap.se/0.6/ wheezy/main amd64 Packages
     0.12.1-1+deb7u1 999
        500 http://security.debian.org/ wheezy/updates/main amd64 Packages
     0.12.1-1 999
        500 http://http.debian.net/debian/ wheezy/main amd64 Packages
```

All good.
