### ISSUE TITLE
As a user I would like to receive mails with a 7bit content transfer encoding

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-user-agent#312]
Background:

When replying to a Mail with Apple Mail, the response caused an error when we try to index it.

Stacktrace:
2015-02-25 11:55:16+0000 [-] FETCH: syncing soledad...
2015-02-25 11:55:16+0000 [-] FETCH soledad SYNCED.
2015-02-25 11:55:16+0000 [-] processing doclist
2015-02-25 11:55:17+0000 [-] Traceback (most recent call last):
2015-02-25 11:55:17+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/adapter/search/__init__.py", line 150, in index_mails
2015-02-25 11:55:17+0000 [-]     self._index_mail(writer, mail)
2015-02-25 11:55:17+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/adapter/search/__init__.py", line 123, in _index_mail
2015-02-25 11:55:17+0000 [-]     mdict = mail.as_dict()
2015-02-25 11:55:17+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/adapter/model/mail.py", line 419, in as_dict
2015-02-25 11:55:17+0000 [-]     'textPlainBody': self.text_plain_body,
2015-02-25 11:55:17+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/adapter/model/mail.py", line 251, in text_plain_body
2015-02-25 11:55:17+0000 [-]     return self._decode_part(self.alternatives[0])
2015-02-25 11:55:17+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/adapter/model/mail.py", line 240, in _decode_part
2015-02-25 11:55:17+0000 [-]     return decoding_map[encoding](part['content'], content_type)
2015-02-25 11:55:17+0000 [-] KeyError: u'7bit'

The email that caused that problem contained this lines:
--Apple-Mail=_2128E4FA-5049-40B4-B227-747398CC8769
Content-Transfer-Encoding: 7bit
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME Versions Identification

Requirements:
When I have a pixelated account
And I sent a Mail with 7bit transfer encoding to it using e.g. Apple Mail
Then I can see the Mail in the Inbox (after some time)

**Comment by lieblingswelt** [comment]
KeyError: u'7bit' also occurred when sending testmails via sendemail script.

**Comment by varac** [comment]
sendemail is a debian package


we tried this, and it produced the 7bit error
```
echo "Your secret message" | gpg -ea -r varac@leap.se | sendemail -f varac@leap.se -t lisa8@leap.se -u 'encrypted with wrong key'
```

**Comment by shyba** [comment]
From varac's example forcing 7bit: **worked.**
Applemail is giving another bug before this line, see #315.

A few suggestions:
* it would be nice to have a 'default' key on decoding_map
* [line 242](https://github.com/pixelated-project/pixelated-user-agent/commit/7a7ab08316b4aa4f7b18b50626cb0dc16dde3efb#diff-298b95861f264eac09bfafa39af47636R242) could check the presence of encoding key before calling it. Maybe a get with a default value?
* is there a better way to generate a 7bit test message? ["encoded_body = body"](https://github.com/pixelated-project/pixelated-user-agent/commit/7a7ab08316b4aa4f7b18b50626cb0dc16dde3efb#diff-0ea52f3ff8b8e69756099f7c0993ee10R216) doesn't seems like the best way to simulate this encoding.
