### ISSUE TITLE
As a user, I dont want to get 'NoneType' object has no attribute ‘endswith' for incoming mails

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-user-agent#315]
Background:
When sending a signed email from external address to alice on try.pixelated from apple mail, the incoming mail caused the attribute error: 'NoneType' object has no attribute ‘endswith' and never appeared on the Pixelated UI.

Traceback (most recent call last):
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-macosx-10.9-intel.egg/twisted/internet/base.py", line 1201, in mainLoop
   self.runUntilCurrent()
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-macosx-10.9-intel.egg/twisted/internet/base.py", line 797, in runUntilCurrent
   f(*a, **kw)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-macosx-10.9-intel.egg/twisted/internet/defer.py", line 382, in callback
   self._startRunCallbacks(result)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-macosx-10.9-intel.egg/twisted/internet/defer.py", line 490, in _startRunCallbacks
   self._runCallbacks()
--- <exception caught here> ---
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-macosx-10.9-intel.egg/twisted/internet/defer.py", line 577, in _runCallbacks
   current.result = callback(current.result, *args, **kw)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/leap.mail-0.3.9_1_gc1f9c92-py2.7.egg/leap/mail/imap/mailbox.py", line 505, in cbNotifyNew
   l.newMessages(exists, recent)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/service/pixelated/adapter/listeners/mailbox_indexer_listener.py", line 39, in newMessages
   self.SEARCH_ENGINE.index_mails(self.querier.mails(missing_idents))
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/service/pixelated/adapter/soledad/soledad_reader_mixin.py", line 68, in mails
   return self._build_mails_from_fdocs(fdocs_chash)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/service/pixelated/adapter/soledad/soledad_reader_mixin.py", line 45, in _build_mails_from_fdocs
   bdoc = self.get_content_by_phash(body_phash)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/service/pixelated/adapter/soledad/soledad_facade_mixin.py", line 27, in get_content_by_phash
   content = self.soledad.get_from_index('by-type-and-payloadhash', 'cnt', phash)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/leap.soledad.client-0.6.3-py2.7.egg/leap/soledad/client/__init__.py", line 973, in get_from_index
   return self._db.get_from_index(index_name, *key_values)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/u1db/backends/sqlite_backend.py", line 670, in get_from_index
   statement, args = self._format_query(definition, key_values)
 File "/Users/ljunger/Documents/Development/DFI/pixelated-project/pixelated-user-agent/pixelated-user-agent-venv/lib/python2.7/site-packages/u1db/backends/sqlite_backend.py", line 641, in _format_query
   if value.endswith('*'):
exceptions.AttributeError: 'NoneType' object has no attribute ‘endswith'

The email that caused that problem contained this lines:
Content-Type: multipart/signed;
Pixelated-encryption-status: false
X-Leap-Signature: invalid;
Apple-Mail=_F5FBDA6A-0B3F-4E0F-9356-80ED05A7B03C
Content-Transfer-Encoding: 7bit\nContent-Disposition: attachment

Requirements:
When sending a signed email from external address to alice on try.pixelated from apple mail,
I expect to see the email in alice's inbox and on the command line, I expect to see synching without errors.
Actually, the incoming mail caused the attribute error: 'NoneType' object has no attribute ‘endswith' (on the command-line) and never appeared on the Pixelated UI.

**Comment by tiagoferraz** [comment]
@lieblingswelt how you get these informations contained in the email?

**Comment by lieblingswelt** [comment]
@tiagoferraz I updated the requirements description, does this help?

**Comment by shyba** [comment]
Some queries on soledad facade were raising error with empty parameters. This is because we were passing this parameter ahead without checking and some documents have null/empty references.

**Comment by tiagoferraz** [comment]
I tested this yesterday while pairing with @shyba and it is working. I also opened defect #321.
