### ISSUE TITLE
Users should be able to send emails

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#319]
I can't send Emails on staging at the moment

##How to reproduce
Login as 'behave-testuser' on staging and try to send 
a mail. You will get an 'problems talking to server'
This is the output of docker:
```
2015-03-12 08:26:12+0000 [SMTPHeloLocalhost,3,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 454, in dataReceived
	    self.lineReceived(line)
	  File "/usr/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 568, in lineReceived
	    return getattr(self, 'state_' + self.mode)(line)
	  File "/usr/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 580, in state_COMMAND
	    method(parts[1])
	  File "/usr/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 687, in do_RCPT
	    d = defer.maybeDeferred(self.validateTo, user)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 943, in validateTo
	    return self.delivery.validateTo(user)
	  File "/usr/lib/python2.7/dist-packages/leap/mail/smtp/gateway.py", line 271, in validateTo
	    self._km.get_key(address, OpenPGPKey)  # might raise KeyNotFound
	  File "/usr/lib/python2.7/dist-packages/leap/keymanager/__init__.py", line 291, in get_key
	    key = self._wrapper_map[ktype].get_key(address, private=private)
	  File "/usr/lib/python2.7/dist-packages/leap/keymanager/openpgp.py", line 299, in get_key
	    doc = self._get_key_doc(address, private)
	  File "/usr/lib/python2.7/dist-packages/leap/keymanager/openpgp.py", line 420, in _get_key_doc
	    'private' if private else 'public')
	  File "/usr/lib/python2.7/dist-packages/leap/common/check.py", line 48, in leap_assert
	    assert condition, message
	exceptions.AssertionError: public
	
2015-03-12 08:26:12+0000 [SMTPSender,client] Stopping factory <twisted.mail.smtp.SMTPSenderFactory instance at 0x7fea23899dd0>
```

## Definition of done
* When sending a mail to self, It should be visible in the inbox
* When sending a mail to outside, it should reach its recipient

**Comment by cz8s** [comment]
folker said its okay to move this to ready

**Comment by cz8s** [comment]
It seems the problem only occurs if I send the email immediately after creating the user and loggin in for the first time

**Comment by fbernitt** [comment]
We did a little bit of investigation while working on issue #313: It seems that the exception above is caused by a problem in the leap keymanager code. The **KeyNotFound** exception is only raised if the nicknym server replies with a 404. For some mail addresses it replies with a different error code, e.g. 500.

In this case the fetch method just returns, but does not store a key in the local soledad database. The next then tries to receive that key because it assumes if no exception had been raised that the key is now available. Therefore this call has to fail.

```python
            ...
            signal(proto.KEYMANAGER_KEY_NOT_FOUND, address)

            # we will only try to fetch a key from nickserver if fetch_remote
            # is True and the key is not private.
            if fetch_remote is False or private is True:
                raise

            signal(proto.KEYMANAGER_LOOKING_FOR_KEY, address)
            self._fetch_keys_from_server(address)  # might raise KeyNotFound
            key = self._wrapper_map[ktype].get_key(address, private=False)
            signal(proto.KEYMANAGER_KEY_FOUND, address)
            ...
```

```python
    def _fetch_keys_from_server(self, address):
        """
        Fetch keys bound to C{address} from nickserver and insert them in
        local database.

        :param address: The address bound to the keys.
        :type address: str

        :raise KeyNotFound: If the key was not found on nickserver.
        """
        # request keys from the nickserver
        res = None
        try:
            res = self._get(self._nickserver_uri, {'address': address})
            res.raise_for_status()
            server_keys = res.json()
            # insert keys in local database
            if self.OPENPGP_KEY in server_keys:
                self._wrapper_map[OpenPGPKey].put_ascii_key(
                    server_keys['openpgp'])
        except requests.exceptions.HTTPError as e:
            if e.response.status_code == 404:
                raise KeyNotFound(address)
            logger.warning("HTTP error retrieving key: %r" % (e,))
            logger.warning("%s" % (res.content,))
        except Exception as e:
            logger.warning("Error retrieving key: %r" % (e,))
```

**Comment by fbernitt** [comment]
You can query the key using this curl call:

```bash
 curl -k -i -X POST -d address=foo@bar.de https://nicknym.staging.pixelated-project.org:6425
```

**Comment by cz8s** [comment]
I opened a bug at leap that they return 500 sometimes:
https://leap.se/code/issues/6789

**Comment by varac** [comment]
ok, tested with new created user, both sending to same account and to outside works.
