### ISSUE TITLE
Bug: Indexing mails sometimes causes LockException

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-user-agent#330]
Why:

Currently when a mail gets indexed sometimes there might be a LockException because of parallel access to the woosh index. When this exception happens, the mail is not indexed and therefore not visibile to the user.

As the mails are re-indexed in a loop, the mail might apear on the next run, but still, this is an annoying problem when testing or trying pixelated for the first time.

Stacktrace:
```
2015-03-12 14:45:34+0000 [-] 172.17.42.1 - - [12/Mar/2015:14:45:34 +0000] "GET /tags HTTP/1.1" 200 408 "https://staging.pixelated-project.org:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) C
hrome/41.0.2272.89 Safari/537.36"
[03-12 14:45:35] 2b0fb0e93aa2 leap.soledad.client.sqlcipher WARNING  Can't defer decryption without first having created a sync db. Falling back to normal syncing mode.
2015-03-12 14:45:35+0000 [-] FETCH: syncing soledad...
2015-03-12 14:45:38+0000 [-] 172.17.42.1 - - [12/Mar/2015:14:45:38 +0000] "GET /contacts?q=foo%40bar.de HTTP/1.1" 200 107 "https://staging.pixelated-project.org:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/53
7.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36"
2015-03-12 14:45:42+0000 [-] FETCH soledad SYNCED.
2015-03-12 14:45:44+0000 [-] Traceback (most recent call last):
2015-03-12 14:45:44+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/adapter/search/__init__.py", line 148, in index_mails
2015-03-12 14:45:44+0000 [-]     with self._index.writer() as writer:
2015-03-12 14:45:44+0000 [-]   File "/usr/lib/python2.7/dist-packages/whoosh/index.py", line 464, in writer
2015-03-12 14:45:44+0000 [-]     return SegmentWriter(self, **kwargs)
2015-03-12 14:45:44+0000 [-]   File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 502, in __init__
2015-03-12 14:45:44+0000 [-]     raise LockError
2015-03-12 14:45:44+0000 [-] LockError
[03-12 14:45:44] 2b0fb0e93aa2 protobuf.socketrpc.server ERROR    4 :
2015-03-12 14:45:44+0000 [HTTPChannel,0,172.17.42.1] 172.17.42.1 - - [12/Mar/2015:14:45:38 +0000] "PUT /mails HTTP/1.1" 200 77 "https://staging.pixelated-project.org:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.
36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36"
2015-03-12 14:45:44+0000 [-] processing doclist
2015-03-12 14:45:44+0000 [HTTPChannel,2,172.17.42.1] Starting factory <twisted.mail.smtp.SMTPSenderFactory instance at 0x7f5856523ab8>
[03-12 14:45:45] 2b0fb0e93aa2 leap.keymanager WARNING  HTTP error retrieving key: HTTPError('500 Server Error: ...',)
[03-12 14:45:45] 2b0fb0e93aa2 leap.keymanager WARNING
2015-03-12 14:45:45+0000 [SMTPHeloLocalhost,0,127.0.0.1] Warning: will send an unencrypted message (because encrypted_only' is set to False).
2015-03-12 14:45:45+0000 [SMTPHeloLocalhost,0,127.0.0.1] Receiving message for delivery: from=folker@staging.pixelated-project.org to=['foo@bar.de']
2015-03-12 14:45:45+0000 [SMTPHeloLocalhost,0,127.0.0.1] Message data complete.
2015-03-12 14:45:45+0000 [SMTPHeloLocalhost,0,127.0.0.1] Will sign the message with 9C1F8FC5DC487C3830598A5B6B0D86614C2578FC.
[03-12 14:45:45] 2b0fb0e93aa2 leap.keymanager WARNING  HTTP error retrieving key: HTTPError('500 Server Error: ...',)
2015-03-12 14:45:45+0000 [SMTPHeloLocalhost,0,127.0.0.1] Will send unencrypted message to folker@bernitt.de.
[03-12 14:45:45] 2b0fb0e93aa2 leap.keymanager WARNING
2015-03-12 14:45:45+0000 [SMTPHeloLocalhost,0,127.0.0.1] 'Unknown content-transfer-encoding: base64'
[03-12 14:45:45] 2b0fb0e93aa2 gnupg        WARNING  No 'default_key' given! Using first key on secring.
2015-03-12 14:45:45+0000 [-] Connecting to SMTP server pixelated.staging.pixelated-project.org:465
2015-03-12 14:45:45+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory instance at 0x7f5856559680>
2015-03-12 14:45:45+0000 [-] None
```

Requirements:

- Its hard to reproduce this problem because it depends on very special timings
- After the fix, the specific exception should no longer occur

**Comment by shyba** [comment]
search performance test succeeded.
Also tested with apache benchmark using 100 concurrent connections asking 100.000 requests while sending mails and tagging old ones. Worked flawlessly.
:D
