### ISSUE TITLE
user-agent should still work when receiving invalid emails

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#331]
## Why

if I receive an email without received headers, the user-agent does not parse any mails anymore.
This is dangerous because it is a possible way to dos a user.

## way to reproduce:
send email with python (see lisas comment)
this is what I get with docker logs:

```
2015-03-17 10:31:27+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 797, in runUntilCurrent
	    f(*a, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/leap/mail/imap/mailbox.py", line 497, in cbNotifyNew
	    l.newMessages(exists, recent)
	  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/listeners/mailbox_indexer_listener.py", line 39, in newMessages
	    self.SEARCH_ENGINE.index_mails(self.querier.mails(missing_idents))
	  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/search/__init__.py", line 150, in index_mails
	    self._index_mail(writer, mail)
	  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/search/__init__.py", line 123, in _index_mail
	    mdict = mail.as_dict()
	  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/model/mail.py", line 427, in as_dict
	    dict_mail = {'header': {k.lower(): v for k, v in self.headers.items()},
	  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/model/mail.py", line 293, in headers
	    _headers['Date'] = self._get_date()
	  File "/usr/lib/python2.7/dist-packages/pixelated/adapter/model/mail.py", line 308, in _get_date
	    date = self.hdoc.content['received'].split(";")[-1].strip()
	exceptions.KeyError: 'received'
```

## Definition of done
whe I send an email with python it should be visible in the user-agent

**Comment by lieblingswelt** [comment]
Python code to send email without received header:
```python
from email.mime.text import MIMEText
import smtplib

    msg = MIMEText('some test')
    msg['Subject'] = 'Unencrypted email'
    msg['From'] = 'behave-testuser@staging.pixelated-project.org'
    msg['To'] = 'behave-testuser@staging.pixelated-project.org'

    s = smtplib.SMTP('staging.pixelated-project.org')
    s.sendmail('behave-testuser@staging.pixelated-project.org', ['behave-testuser@staging.pixelated-project.org'], msg.as_string())
    s.quit()
```

**Comment by cz8s** [comment]
thats why staging is red now

**Comment by lieblingswelt** [comment]
tested via python smtplib worked.
