### ISSUE TITLE
the process to validate the provider should work with an official certificate

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#333]
## why
if you use a cert that was bought from an official ssl company, our platform does not work anymore

## explanation
every leap client has to validate the provider in a three step process.
1: Download https://provider:443/provider.json
2: Download the ca linked in the provider.json
3: use that ca to validate the connection to soledad/smtp/etc

The only time we need to provide a fingerprint or ca to help the client to validate something is when https://provider:443 can not be validated otherwise.
And in this case, the fingerprint or ca we provided MUST only be used to validated https://provider:443. For every other connection the ca linked in the provider.json MUST be used

## definition of done
try.pixelated has to work with a valid certificate

**Comment by cz8s** [comment]
Here is a workflow how to validate a provider:

![img_20150319_094725](https://cloud.githubusercontent.com/assets/369402/6727091/b5ca5ff2-ce1e-11e4-98fb-3a439eb09cf4.jpg)

**Comment by fbernitt** [comment]
Just as an addition: For Secure Remote Password the same verification as for the 'get provider.json' has to be used.

**Comment by tiagoferraz** [comment]
It's working in my venv, but it's not working in my vagrant box.
```shell
2015-04-07 19:47:19+0000 [-] Site starting on 3333
2015-04-07 19:47:19+0000 [-] Starting factory <twisted.web.server.Site instance at 0x4b0a518>
2015-04-07 19:47:27+0000 [-] Unhandled error in Deferred:
2015-04-07 19:47:27+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
	    self.__bootstrap_inner()
	  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 505, in run
	    self.__target(*self.__args, **self.__kwargs)
	--- <exception caught here> ---
	  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 191, in _worker
	    result = context.call(ctx, function, *args, **kwargs)
	  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/vagrant/service/pixelated/config/__init__.py", line 66, in init_soledad
	    return init_soledad_and_user_key(app, args.home)
	  File "/vagrant/service/pixelated/config/soledad.py", line 24, in init_soledad_and_user_key
	    leap_home)
	  File "/vagrant/service/pixelated/bitmask_libraries/session.py", line 41, in open
	    provider = LeapProvider(server_name, config)
	  File "/vagrant/service/pixelated/bitmask_libraries/provider.py", line 29, in __init__
	    self.provider_json = self.fetch_provider_json()
	  File "/vagrant/service/pixelated/bitmask_libraries/provider.py", line 109, in fetch_provider_json
	    response = self._validated_get(url)
	  File "/vagrant/service/pixelated/bitmask_libraries/provider.py", line 101, in _validated_get
	    response = session.get(url, verify=which_bootstrap_CA_bundle(self), timeout=self.config.timeout_in_s)
	  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 369, in get
	    return self.request('GET', url, **kwargs)
	  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 357, in request
	    resp = self.send(prep, **send_kwargs)
	  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 460, in send
	    r = adapter.send(request, **kwargs)
	  File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/adapters.py", line 358, in send
	    raise SSLError(e)
	requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
	

```

**Comment by shyba** [comment]
I found a small error and fixed locally. Can you retest please?

2015-04-07 16:46 GMT-03:00 Tiago Ferraz <notifications@github.com>:

> It's working in my venv, but it's not working in my vagrant box.
>
> 2015-04-07 19:47:19+0000 [-] Site starting on 3333
> 2015-04-07 19:47:19+0000 [-] Starting factory <twisted.web.server.Site instance at 0x4b0a518>
> 2015-04-07 19:47:27+0000 [-] Unhandled error in Deferred:
> 2015-04-07 19:47:27+0000 [-] Unhandled Error
>     Traceback (most recent call last):
>       File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
>         self.__bootstrap_inner()
>       File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
>         self.run()
>       File "/usr/lib/python2.7/threading.py", line 505, in run
>         self.__target(*self.__args, **self.__kwargs)
>     --- <exception caught here> ---
>       File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 191, in _worker
>         result = context.call(ctx, function, *args, **kwargs)
>       File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
>         return self.currentContext().callWithContext(ctx, func, *args, **kw)
>       File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
>         return func(*args,**kw)
>       File "/vagrant/service/pixelated/config/__init__.py", line 66, in init_soledad
>         return init_soledad_and_user_key(app, args.home)
>       File "/vagrant/service/pixelated/config/soledad.py", line 24, in init_soledad_and_user_key
>         leap_home)
>       File "/vagrant/service/pixelated/bitmask_libraries/session.py", line 41, in open
>         provider = LeapProvider(server_name, config)
>       File "/vagrant/service/pixelated/bitmask_libraries/provider.py", line 29, in __init__
>         self.provider_json = self.fetch_provider_json()
>       File "/vagrant/service/pixelated/bitmask_libraries/provider.py", line 109, in fetch_provider_json
>         response = self._validated_get(url)
>       File "/vagrant/service/pixelated/bitmask_libraries/provider.py", line 101, in _validated_get
>         response = session.get(url, verify=which_bootstrap_CA_bundle(self), timeout=self.config.timeout_in_s)
>       File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 369, in get
>         return self.request('GET', url, **kwargs)
>       File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 357, in request
>         resp = self.send(prep, **send_kwargs)
>       File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/sessions.py", line 460, in send
>         r = adapter.send(request, **kwargs)
>       File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/requests-2.0.0-py2.7.egg/requests/adapters.py", line 358, in send
>         raise SSLError(e)
>     requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated-project/pixelated-user-agent/issues/333#issuecomment-90710565>
> .
>



-- 
Victor Shyba

**Comment by tiagoferraz** [comment]
I started a user agent and sucessfully connected to staging.
