### ISSUE TITLE
Reset data on a demo account

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#345]
## Why
The demo accounts in try.pixelated-project.org will become polluted with test data over time. We should be able to clear the messages of those accounts and reload a predefined set of messages.

## Definition of Done
Given there's some data on a demo account that is different from the standard preoloaded data
When an admin triggers a reset
Then the demo account have only the preloaded data

## Notes
Depends on #335

**Comment by cz8s** [comment]
I tried to qa, but I got a strange error:
'''
root@53e8b0c8a9a1:/# pixelated-maintenance reset 
2015-04-15 14:28:51+0000 [-] Log opened.



^C2015-04-15 14:30:36+0000 [-] Traceback (most recent call last):
2015-04-15 14:30:36+0000 [-]   File "/usr/bin/pixelated-maintenance", line 9, in <module>
2015-04-15 14:30:36+0000 [-]     load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-maintenance')()
2015-04-15 14:30:36+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/maintenance.py", line 72, in initialize
2015-04-15 14:30:36+0000 [-]     config_dispatcher(app, args)
2015-04-15 14:30:36+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/config/dispatcher.py", line 34, in config_dispatcher
2015-04-15 14:30:36+0000 [-]     config = fetch_credentials_from_dispatcher(args.dispatcher) if args.dispatcher else fetch_credentials_from_dispatcher_stdin()
2015-04-15 14:30:36+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/config/dispatcher.py", line 32, in fetch_credentials_from_dispatcher_stdin
2015-04-15 14:30:36+0000 [-]     return json.loads(sys.stdin.read())
2015-04-15 14:30:36+0000 [-] KeyboardInterrupt
'''

So the command started and seemed to wait for some input. But which input? 
Username? password?

**Comment by tiagoferraz** [comment]
It would be good an email about this new feature on dispatcher.

**Comment by cz8s** [comment]
I now get a ' Main loop terminated'
The mails get purged and everything seems to work.
But the feedback might be improved :)

**Comment by rafaelzlisboa** [comment]
how to run this from the dispatcher?

**Comment by tiagoferraz** [comment]
This does not work if the user is logged in the provider. Was this foreseen?
