### ISSUE TITLE
error importing protobuf_socket

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#408]
When starting pixelated-user-agent from the package inside docker on staging,
it complains that it can't load extensions.protobuf_socket

```
root@8eb1dbab31c2:/# pixelated-user-agent 
2015-06-09 10:46:58 [twisted] INFO Site starting on 3333
2015-06-09 10:46:58 [twisted] INFO Starting factory <twisted.web.server.Site instance at 0x7fa6d70fee18>
2015-06-09 10:46:58 [twisted] ERROR Traceback (most recent call last):
Traceback (most recent call last):
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
2015-06-09 10:46:58 [twisted] ERROR     self.__bootstrap_inner()
    self.__bootstrap_inner()
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2015-06-09 10:46:58 [twisted] ERROR     self.run()
    self.run()
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/lib/python2.7/threading.py", line 763, in run
2015-06-09 10:46:58 [twisted] ERROR     self.__target(*self.__args, **self.__kwargs)
    self.__target(*self.__args, **self.__kwargs)
2015-06-09 10:46:58 [twisted] ERROR --- <exception caught here> ---
--- <exception caught here> ---
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 196, in _worker
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 196, in _worker
2015-06-09 10:46:58 [twisted] ERROR     result = context.call(ctx, function, *args, **kwargs)
    result = context.call(ctx, function, *args, **kwargs)
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
2015-06-09 10:46:58 [twisted] ERROR     return self.currentContext().callWithContext(ctx, func, *args, **kw)
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
2015-06-09 10:46:58 [twisted] ERROR     return func(*args,**kw)
    return func(*args,**kw)
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/dist-packages/pixelated/application.py", line 74, in <lambda>
  File "/usr/lib/python2.7/dist-packages/pixelated/application.py", line 74, in <lambda>
2015-06-09 10:46:58 [twisted] ERROR     args.leap_home))
    args.leap_home))
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/dist-packages/pixelated/config/leap.py", line 16, in initialize_leap
  File "/usr/lib/python2.7/dist-packages/pixelated/config/leap.py", line 16, in initialize_leap
2015-06-09 10:46:58 [twisted] ERROR     init_monkeypatches()
    init_monkeypatches()
2015-06-09 10:46:58 [twisted] ERROR   File "/usr/lib/python2.7/dist-packages/pixelated/config/leap.py", line 33, in init_monkeypatches
  File "/usr/lib/python2.7/dist-packages/pixelated/config/leap.py", line 33, in init_monkeypatches
2015-06-09 10:46:58 [twisted] ERROR     import pixelated.extensions.protobuf_socket
    import pixelated.extensions.protobuf_socket
2015-06-09 10:46:58 [twisted] ERROR exceptions.ImportError: No module named extensions.protobuf_socket
exceptions.ImportError: No module named extensions.protobuf_socket
2015-06-09 10:46:58 [twisted] INFO (TCP Port 3333 Closed)
2015-06-09 10:46:58 [twisted] INFO Stopping factory <twisted.web.server.Site instance at 0x7fa6d70fee18>
2015-06-09 10:46:58 [twisted] INFO Main loop terminated.
```

**Comment by cz8s** [comment]
This bug seems to be introduced by 68acde0220c3f895300b5491f941ca611212a206

**Comment by bwgpro** [comment]
I added the new folder to the setup.py, we had missed that. It should work on the next build

**Comment by cz8s** [comment]
thanks a lot. Seems to work on staging
